# RBAC model configuration for Casbin
# 用户， 资源（接口路径）， 操作（请求方法）
[request_definition]
r = sub, obj, act

# 角色, 路径, 方法
[policy_definition]
p = sub, obj, act

# 用户和角色的绑定关系 alice -> admin
[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

# 最终匹配规则
[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "*")
